// Generated by CoffeeScript 1.6.2
(function() {
  var Server;

  Server = (function() {
    Server.prototype.config = {
      aliases: [
        {
          jade: 'html',
          less: 'css',
          sass: 'css',
          scss: 'css',
          styl: 'css',
          coffee: 'js'
        }
      ],
      applyJsLive: false,
      applyCssLive: true,
      debug: true,
      delay: 0,
      exclusions: ['.git/', '.svn/', '.hg/'],
      extensions: ['html', 'jade', 'css', 'less', 'sass', 'scss', 'styl', 'js', 'coffee', 'png', 'gif', 'jpg', 'php', 'php5', 'phtml', 'py', 'rb', 'erb'],
      port: 35729
    };

    Server.prototype.sockets = [];

    function Server(config) {
      var attr, value, _i, _len;

      for (attr = _i = 0, _len = config.length; _i < _len; attr = ++_i) {
        value = config[attr];
        this.config[attr] = value;
      }
    }

    Server.prototype.debug = function(string) {
      if (this.config.debug) {
        return console.log(str);
      }
    };

    return Server;

  })();

}).call(this);
